apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-page-replicator
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-page-replicator
  template:
    metadata:
      labels:
        app: login-page-replicator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      serviceAccountName: gke-app-sa
      containers:
        - name: app
          image: europe-west1-docker.pkg.dev/pfe-esprit-489411/login-page-replicator-repo/login-page-replicator:825da00
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.1.0
          args:
            - -nginx.scrape-uri=http://localhost/stub_status
          ports:
            - containerPort: 9113
              name: metrics
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi

