apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-app
  namespace: observability
  labels:
    # Must match kube-prometheus-stack helm release name
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: login-page-replicator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
